name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Configure Python
      env:
        BUILD_NUM: ${{ github.run_id }}
      run: |
        # Install dependencies required to load ivpm.yaml file
        python3 -m pip install setuptools wheel
        #python3 -m ivpm update -a
        echo "BUILD_NUM=${BUILD_NUM}" > src/zuspec/__build_num__.py
        python3 setup.py bdist_wheel --universal

        #    - name: Build Docs
        #      run: |
        #        ./packages/python/bin/sphinx-build -M html ./doc/source build
        #        touch build/html/.nojekyll

    - name: Publish to PyPi
      if: startsWith(github.ref, 'refs/heads/main')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        #    - name: Publish Docs
        #      if: startsWith(github.ref, 'refs/heads/main')
        #      uses: JamesIves/github-pages-deploy-action@4.1.7
        #      with:
        #        branch: gh-pages
        #        folder: build/html


